Settings As screen:

    Label9 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =136
        Size: =50
        Text: ="SETTINGS"
        Width: =560
        X: =32
        Y: =48
        ZIndex: =1

    Icon12 As icon.People:
        Color: =RGBA(0, 0, 0, 1)
        Height: =60
        Icon: =Icon.People
        Width: =97
        X: =16
        Y: =243
        ZIndex: =2

    Icon13 As icon.Bell:
        Color: =RGBA(0, 0, 0, 1)
        Height: =70
        Icon: =Icon.Bell
        Width: =97
        X: =16
        Y: =329
        ZIndex: =3

    Icon14 As icon.Lock:
        Color: =RGBA(0, 0, 0, 1)
        Height: =69
        Icon: =Icon.Lock
        Width: =97
        X: =16
        Y: =423
        ZIndex: =4

    Icon16 As icon.Globe:
        Color: =RGBA(0, 0, 0, 1)
        Height: =70
        Icon: =Icon.Globe
        Width: =97
        X: =16
        Y: =524
        ZIndex: =5

    Icon17 As icon.Person:
        Color: =RGBA(0, 0, 0, 1)
        Height: =70
        Icon: =Icon.Person
        Width: =97
        X: =16
        Y: =623
        ZIndex: =6

    Icon18 As icon.Help:
        Color: =RGBA(0, 0, 0, 1)
        Height: =68
        Icon: =Icon.Help
        Width: =97
        X: =15
        Y: =721
        ZIndex: =7

    Icon19 As icon.Information:
        Color: =RGBA(0, 0, 0, 1)
        Height: =70
        Icon: =Icon.Information
        Width: =97
        X: =16
        Y: =814
        ZIndex: =8

    Icon20 As icon.ColorPicker:
        Color: =RGBA(0, 0, 0, 1)
        Height: =75
        Icon: =Icon.ColorPicker
        Width: =97
        X: =16
        Y: =909
        ZIndex: =9

    Icon21 As icon.Leave:
        Color: =RGBA(0, 0, 0, 1)
        Height: =66
        Icon: =Icon.Leave
        Width: =97
        X: =32
        Y: =1018
        ZIndex: =10

    Label8_12 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        Font: =Font.Arial
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Invite friends"
        Width: =490
        X: =150
        Y: =237
        ZIndex: =11

    Label8_13 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Privacity"
        Width: =490
        X: =150
        Y: =437
        ZIndex: =12

    Label8_14 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Account"
        Width: =490
        X: =150
        Y: =629
        ZIndex: =13

    Label8_15 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: =""
        Width: =490
        X: =113
        Y: =896
        ZIndex: =14

    Label8_16 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Languages"
        Width: =490
        X: =150
        Y: =527
        ZIndex: =15

    Label8_17 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Help"
        Width: =490
        X: =150
        Y: =718
        ZIndex: =16

    Label8_18 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Info"
        Width: =490
        X: =150
        Y: =814
        ZIndex: =17

    Label8_19 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        Font: =Font.Arial
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Notifications"
        Width: =490
        X: =150
        Y: =331
        ZIndex: =18

    Label8_20 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Exit all accounts"
        Width: =490
        X: =150
        Y: =1018
        ZIndex: =19

    Label8_21 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =3
        FontWeight: =FontWeight.Semibold
        Height: =66
        Size: =30
        Text: ="Topics"
        Width: =490
        X: =150
        Y: =909
        ZIndex: =20

    Icon22 As icon.Home:
        Color: =RGBA(0, 0, 0, 1)
        Icon: =Icon.Home
        X: =539
        Y: =23
        ZIndex: =21

